name = "white-band-6525"
main = "src/index.ts"
compatibility_date = "2023-10-10"

[[queues.producers]]
 queue = "test-queue"
 binding = "TEST_QUEUE"

 [[queues.consumers]]
 queue = "test-queue"
 # Required: this should match the name of the queue you created in step 3.
 # If you misspell the name, you will receive an error when attempting to publish your Worker.
 max_batch_size = 10 # optional: defaults to 10
 max_batch_timeout = 5 # optional: defaults to 5 seconds